---
- name: generate a file for motd
  hosts: all
  become: yes
  tasks:
    - name: copy motd file to /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
